[project]
name = "rulezet-core"
version = "0.1.0"
description = "Community-Driven Detection Rules Platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "apscheduler>=3.11.3",
    "dotenv>=0.9.9",
    "email-validator>=2.3.0",
    "faiss-cpu>=1.14.2",
    "flask>=3.1.3",
    "flask-login>=0.6.3",
    "flask-mail>=0.10.0",
    "flask-migrate>=4.1.0",
    "flask-restx>=1.3.2",
    "flask-session>=0.8.0",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.3.0",
    "gitpython>=3.1.50",
    "gunicorn>=26.0.0",
    "idstools>=0.6.5",
    "jsonschema>=4.26.0",
    "markdown>=3.10.2",
    "msc-pyparser>=1.2.2",
    "nova-hunting>=0.1.4",
    "psycopg2-binary>=2.9.12",
    "pymisp>=2.5.34.1",
    "pysigma>=1.4.0",
    "python-dateutil>=2.9.0.post0",
    "pyyaml>=6.0.3",
    "rapidfuzz>=3.14.5",
    "requests>=2.34.2",
    "schedule>=1.2.2",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.50",
    "suricataparser>=1.0.0",
    "weasyprint>=69.0",
    "werkzeug>=3.1.8",
    "wtforms>=3.2.2",
    "yara-python>=4.5.4",
    "zeekscript>=1.3.6",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]
