"""add endpoint_uuid version last_started_at to instance_config

Revision ID: 08a4650ed482
Revises: 9c8ec47ceb14
Create Date: 2026-06-10 15:34:38.971184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a4650ed482'
down_revision = '9c8ec47ceb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_started_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instance_config_endpoint_uuid'), ['endpoint_uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_config_endpoint_uuid'))
        batch_op.drop_column('last_started_at')
        batch_op.drop_column('version')
        batch_op.drop_column('endpoint_uuid')

    # ### end Alembic commands ###
