"""empty message

Revision ID: 0b1c535cf9e3
Revises: 431e858dffaf
Create Date: 2026-05-04 08:11:34.878698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1c535cf9e3'
down_revision = '431e858dffaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['background_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_job_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_log_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_job_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_log_job_id'))

    op.drop_table('background_job_log')
    # ### end Alembic commands ###
