"""add connector icon owner_mode is_system

Revision ID: 17459f27d874
Revises: ebfe6b7e422b
Create Date: 2026-06-09 11:25:39.713121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17459f27d874'
down_revision = 'ebfe6b7e422b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('owner_mode', sa.String(length=16), nullable=False,
                                      server_default='shadow'))
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_connector_is_system'), ['is_system'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_is_system'))
        batch_op.drop_column('is_system')
        batch_op.drop_column('owner_mode')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
