"""add rule_scope table

Revision ID: 19550901f18b
Revises: 7b2258988f53
Create Date: 2026-06-01 13:49:34.892009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19550901f18b'
down_revision = '7b2258988f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('works', sa.Boolean(), nullable=False),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'user_id', name='uq_rule_scope_user')
    )
    with op.batch_alter_table('rule_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_scope_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_scope_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_scope', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_scope_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_scope_rule_id'))

    op.drop_table('rule_scope')
    # ### end Alembic commands ###
