"""comment replies reactions rule

Revision ID: 1db2c14335d3
Revises: 40499c765ba4
Create Date: 2026-06-01 11:19:16.714525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db2c14335d3'
down_revision = '40499c765ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_comment_reaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_comment_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_comment_reaction_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('parent_comment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comment_uuid'), ['uuid'], unique=True)
        batch_op.create_foreign_key(None, 'comment', ['parent_comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comment_uuid'))
        batch_op.drop_column('parent_comment_id')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('rule_comment_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_comment_reaction_uuid'))

    op.drop_table('rule_comment_reaction')
    # ### end Alembic commands ###
