"""empty message

Revision ID: 431e858dffaf
Revises: c1803d39d883
Create Date: 2026-04-30 14:34:57.470900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431e858dffaf'
down_revision = 'c1803d39d883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('done', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_job_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_job_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_job_uuid'))
        batch_op.drop_index(batch_op.f('ix_background_job_status'))
        batch_op.drop_index(batch_op.f('ix_background_job_job_type'))

    op.drop_table('background_job')
    # ### end Alembic commands ###
