"""add sync_instance_url to rule

Revision ID: 750f1bc1e78c
Revises: 17459f27d874
Create Date: 2026-06-09 15:19:07.796249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750f1bc1e78c'
down_revision = '17459f27d874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_instance_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('sync_instance_url')

    # ### end Alembic commands ###
