"""drop endpoint_uuid use uuid as stable registry id

Revision ID: 8b0b888f8d0d
Revises: 08a4650ed482
Create Date: 2026-06-10 15:57:06.398402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0b888f8d0d'
down_revision = '08a4650ed482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_config_endpoint_uuid'))
        batch_op.drop_column('endpoint_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_instance_config_endpoint_uuid'), ['endpoint_uuid'], unique=False)

    # ### end Alembic commands ###
