"""add instance_config and registered_instance tables

Revision ID: 9c8ec47ceb14
Revises: d09cf0bc08a2
Create Date: 2026-06-10 13:54:34.597609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8ec47ceb14'
down_revision = 'd09cf0bc08a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('telemetry_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('registered_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('public_url', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('rules_count', sa.Integer(), nullable=True),
    sa.Column('bundles_count', sa.Integer(), nullable=True),
    sa.Column('ping_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registered_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_instance_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_registered_instance_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_instance_uuid'))
        batch_op.drop_index(batch_op.f('ix_registered_instance_last_seen'))

    op.drop_table('registered_instance')
    op.drop_table('instance_config')
    # ### end Alembic commands ###
