"""add remote_rules_count and remote_bundles_count to connector

Revision ID: d09cf0bc08a2
Revises: 750f1bc1e78c
Create Date: 2026-06-10 13:20:20.276911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09cf0bc08a2'
down_revision = '750f1bc1e78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remote_rules_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remote_bundles_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_column('remote_bundles_count')
        batch_op.drop_column('remote_rules_count')

    # ### end Alembic commands ###
