"""add connector model and origin fields on rule and bundle

Revision ID: ebfe6b7e422b
Revises: 31e4523a751b
Create Date: 2026-06-09 10:33:57.805981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe6b7e422b'
down_revision = '31e4523a751b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('instance_url', sa.String(length=512), nullable=False),
    sa.Column('api_key_outbound', sa.String(length=512), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shadow_user_id', sa.Integer(), nullable=True),
    sa.Column('sync_rules', sa.Boolean(), nullable=False),
    sa.Column('sync_bundles', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('rules_synced', sa.Integer(), nullable=False),
    sa.Column('bundles_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shadow_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_connector_type'), ['connector_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connector_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remote_bundle_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_bundle_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundle_remote_bundle_uuid'), ['remote_bundle_uuid'], unique=False)
        batch_op.create_foreign_key(None, 'connector', ['connector_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connector_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remote_rule_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_rule_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_remote_rule_uuid'), ['remote_rule_uuid'], unique=False)
        batch_op.create_foreign_key(None, 'connector', ['connector_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rule_remote_rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_connector_id'))
        batch_op.drop_column('remote_rule_uuid')
        batch_op.drop_column('connector_id')

    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bundle_remote_bundle_uuid'))
        batch_op.drop_index(batch_op.f('ix_bundle_connector_id'))
        batch_op.drop_column('remote_bundle_uuid')
        batch_op.drop_column('connector_id')

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_uuid'))
        batch_op.drop_index(batch_op.f('ix_connector_connector_type'))

    op.drop_table('connector')
    # ### end Alembic commands ###
